spec/spec_helper.rb:
    mock_with: ':rspec'

Gemfile:
  required:
    ':development':
      - gem: puppet-strings

appveyor.yml:
  delete: true

.travis.yml:
  remove_includes:
    - env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9

.rspec:
  delete: true

.gitlab-ci.yml:
  delete: true
